package c22_exception

fun main() {
    throw Exception("에러가 발생했습니다.")
}